//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KienAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tb_ProductCategory tb_ProductCategory { get; set; }
    }
}
